['Let', "'s", 'learn', 'NLP', '!']


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [ ]:
from sklearn.preprocessing import LabelEncoder

data = ['Red', 'Green', 'Blue', 'Red' , 'White' , 'Orange']

le = LabelEncoder()
encoded_data = le.fit_transform(data)
print(f"Encoded Data: {encoded_data}")

Encoded Data: [3 1 0 3 4 2]


In [ ]:
from sklearn.preprocessing import LabelEncoder

data = ['cat', 'cow', 'Rat', 'dog' , 'bird' , 'animal']

le = LabelEncoder()
encoded_data = le.fit_transform(data)
print(f"Encoded Data: {encoded_data}")

Encoded Data: [3 4 0 5 2 1]


In [ ]:
sentence = "Label Encoding is important because many ML algorithms cannot process string values (Categorical Data) directly. Hence, converting them into numerical values is essential for model training. Categorical data is broadly divided into two types"
result = sentence.split ( sep =" " )
print(result)

['Label', 'Encoding', 'is', 'important', 'because', 'many', 'ML', 'algorithms', 'cannot', 'process', 'string', 'values', '(Categorical', 'Data)', 'directly.', 'Hence,', 'converting', 'them', 'into', 'numerical', 'values', 'is', 'essential', 'for', 'model', 'training.', 'Categorical', 'data', 'is', 'broadly', 'divided', 'into', 'two', 'types']


In [ ]:
sentence = "Label Encoding is important because many ML algorithms cannot process string values Categorical Data directly ? Hence, converting them into numerical values is essential for model training. Categorical data is broadly divided into two types"
result = sentence.split ( sep =" " )
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
encoded_data = le.fit_transform(result)
print(f"Encoded Data: {encoded_data}")
decoded_data = le.inverse_transform(encoded_data)
print(f"Decoded Data: {decoded_data}")
print(f" Result is :{result}")

Encoded Data: [ 5  3 19 17  8 20  6  7 10 23 24 29  1  2 13  0  4 11 25 18 22 29 19 15
 16 21 26  1 12 19  9 14 18 27 28]
Decoded Data: ['Label' 'Encoding' 'is' 'important' 'because' 'many' 'ML' 'algorithms'
 'cannot' 'process' 'string' 'values' 'Categorical' 'Data' 'directly' '?'
 'Hence,' 'converting' 'them' 'into' 'numerical' 'values' 'is' 'essential'
 'for' 'model' 'training.' 'Categorical' 'data' 'is' 'broadly' 'divided'
 'into' 'two' 'types']
 Result is :['Label', 'Encoding', 'is', 'important', 'because', 'many', 'ML', 'algorithms', 'cannot', 'process', 'string', 'values', 'Categorical', 'Data', 'directly', '?', 'Hence,', 'converting', 'them', 'into', 'numerical', 'values', 'is', 'essential', 'for', 'model', 'training.', 'Categorical', 'data', 'is', 'broadly', 'divided', 'into', 'two', 'types']


In [ ]:
import nltk
nltk.download('punkt_tab')
sentence = "If the categories have a clear order, then use Label Encoding otherwise use?"
from nltk.tokenize import word_tokenize
result = word_tokenize(sentence)
print(result)

['If', 'the', 'categories', 'have', 'a', 'clear', 'order', ',', 'then', 'use', 'Label', 'Encoding', 'otherwise', 'use', '?']


[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

words = np.array(["Label", "Encoding", "is", "important", "because", "many", "ML", "algorithms"]).reshape(-1, 1)

encoder = OneHotEncoder(sparse_output=False)
encoded = encoder.fit_transform(words)

print("Categories:", encoder.categories_[0])
print(encoded)

Categories: ['Encoding' 'Label' 'ML' 'algorithms' 'because' 'important' 'is' 'many']
[[0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]]
